all: HW05

HW05: 
	g++ -std=c++0x -c caner_akin_151044066.cpp
	g++ -std=c++0x -c read_file.cpp
	g++ -std=c++0x -c University.cpp	
	g++ -std=c++0x -c Employee.cpp
	g++ -std=c++0x -c AcademicPersonnel.cpp
	g++ -std=c++0x -c AdministrativePersonnel.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c ResearchAssistant.cpp
	g++ -std=c++0x -c Secretary.cpp
	g++ -std=c++0x -c Officer.cpp

	g++ -o HW05 caner_akin_151044066.o read_file.o University.o Employee.o AcademicPersonnel.o AdministrativePersonnel.o Lecturer.o ResearchAssistant.o Secretary.o Officer.o

	./HW05

clean:
	rm *.o HW05
