all: HW03

HW03: 
	g++ -std=c++0x -c caner_akin_151044066.cpp
	g++ -std=c++0x -c Course.cpp
	g++ -std=c++0x -c Classroom.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c Administrator.cpp
	g++ -std=c++0x -c read_file.cpp	
	g++ -std=c++0x -c operation.cpp	
	
	g++ -o HW03 caner_akin_151044066.o Course.o Classroom.o Lecturer.o Administrator.o read_file.o operation.o

	./HW03

clean:
	rm *.o HW03 
