all: HW07

HW07: 
	g++ -std=c++11 -c caner_akin_151044066.cpp
	g++ -std=c++11 -c System.cpp
	g++ -std=c++11 -c University.cpp	
	g++ -std=c++11 -c Employee.cpp
	g++ -std=c++11 -c Lecturer.cpp
	g++ -std=c++11 -c ResearchAssistant.cpp
	g++ -std=c++11 -c Secretary.cpp
	g++ -std=c++11 -c Officer.cpp
	g++ -std=c++11 -c EducationSystem.cpp
	g++ -std=c++11 -c CommunistEducation.cpp
	g++ -std=c++11 -c LiberalEducation.cpp
	g++ -std=c++11 -c CapitalistEducation.cpp

	g++ -o HW07 caner_akin_151044066.o System.o University.o Employee.o Lecturer.o ResearchAssistant.o Secretary.o Officer.o EducationSystem.o CommunistEducation.o LiberalEducation.o CapitalistEducation.o

	./HW07

clean:
	rm *.o HW07
