all: HW06

HW06: 
	g++ -std=c++0x -c caner_akin_151044066.cpp
	g++ -std=c++0x -c read_file.cpp
	g++ -std=c++0x -c University.cpp	
	g++ -std=c++0x -c Employee.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c ResearchAssistant.cpp
	g++ -std=c++0x -c Secretary.cpp
	g++ -std=c++0x -c Officer.cpp
	g++ -std=c++0x -c Yok.cpp

	g++ -o HW06 caner_akin_151044066.o read_file.o University.o Employee.o Lecturer.o ResearchAssistant.o Secretary.o Officer.o Yok.o

	./HW06

clean:
	rm *.o HW06
