all: HW04

HW04: 
	g++ -std=c++0x -c caner_akin_151044066.cpp
	g++ -std=c++0x -c Course.cpp
	g++ -std=c++0x -c Classroom.cpp
	g++ -std=c++0x -c Lecturer.cpp
	g++ -std=c++0x -c read_file.cpp	
	g++ -std=c++0x -c Student.cpp
	g++ -std=c++0x -c Administrator.cpp
	g++ -std=c++0x -c operation.cpp	
	
	g++ -o HW04 caner_akin_151044066.o Course.o Classroom.o Lecturer.o read_file.o Student.o Administrator.o operation.o

	./HW04

clean:
	rm *.o HW04
